//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIHMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BlockList
    {
        public long Id { get; set; }
        public string BlockedIp { get; set; }
        public System.DateTime Expiration { get; set; }
        public bool Explicit { get; set; }
        public string Reason { get; set; }
    }
}
