//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIHMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbGamePlatform
    {
        public Nullable<int> GameId { get; set; }
        public Nullable<int> PlatformId { get; set; }
        public int Id { get; set; }
    
        public virtual DbGame DbGame { get; set; }
        public virtual DbPlatform DbPlatform { get; set; }
    }
}
