//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIHMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DbGameWithRating
    {
        public string Name { get; set; }
        public string Summary { get; set; }
        public string Rating { get; set; }
        public string RatingExplanation { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string SmallImageUrl { get; set; }
        public string ThumbImageUrl { get; set; }
        public string GbSiteDetailUrl { get; set; }
        public string PlatformName { get; set; }
        public string PlatformIcon { get; set; }
        public string PlatformAbbreviation { get; set; }
        public int GameId { get; set; }
        public int PlatformId { get; set; }
    }
}
