//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIHMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PendingGameLink
    {
        public long Id { get; set; }
        public int PendingSubmissionId { get; set; }
        public string Link { get; set; }
    
        public virtual PendingSubmission PendingSubmission { get; set; }
    }
}
