//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DIHMT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ThumbImage
    {
        public long Id { get; set; }
        public int GameId { get; set; }
        public string ContentType { get; set; }
        public System.DateTime LastUpdated { get; set; }
        public string ImageUrl { get; set; }
    
        public virtual DbGame DbGame { get; set; }
    }
}
